# Site settings
title: "Parveez Banu Syed Azizuddin"
description: "Robotics Engineer Portfolio | ROS 2, Embedded Systems, Automation"
url: "https://parveezsyed28.github.io"      # Replace with your GitHub Pages URL
baseurl: ""                             

# Theme
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default"

# Plugins (required by Minimal Mistakes)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Author info (optional)
author:
  name: "Parveez Banu Syed Azizuddin"
  email: "parveezbanu.s@gmail.com"

# Navigation links
nav:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects/
  - title: "Contact"
    url: /contact/

# Markdown and highlighting
markdown: kramdown
highlighter: rouge

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Syntax highlighting with line numbers (optional)
rouge:
  line_numbers: true

