title: "Parveez Banu Syed Azizuddin"
description: "Robotics Engineer Portfolio | ROS 2, Embedded Systems"
baseurl: "" 
url: "https://parveezsyed28.github.io" 

# Theme
theme: jekyll-theme-slate

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Navigation Bar
header_pages:
  - index.md

nav:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /#projects
  - title: "Skills"
    url: /#skills
  - title: "Contact"
    url: /#contact

# Author Info
author:
  name: "Parveez Banu Syed Azizuddin"
  email: "parveezbanu.s@gmail.com"

# Markdown & Highlighting
markdown: kramdown
highlighter: rouge

# Rouge Syntax Options
rouge:
  line_numbers: true

# Exclude from site build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
